apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chuzone-app-ingress
  namespace: examen-26
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - YOUR_DOMAIN.duckdns.org
    secretName: chuzone-app-tls
  rules:
  - host: YOUR_DOMAIN.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chuzone-app-service
            port:
              number: 80
