apiVersion: v1
kind: Service
metadata:
  name: chuzone-app-service
  namespace: examen-26
  labels:
    app: chuzone-app
spec:
  type: NodePort
  selector:
    app: chuzone-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    nodePort: 30080
