name: Release Approve

on:
  push:
    branches:
      - main

jobs:
  promote-release:
    name: Promote Release to 1.0.0
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull RC image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/chuzone-app:1.0.0-RC1

      - name: Tag stable release
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/chuzone-app:1.0.0-RC1 ${{ secrets.DOCKER_USERNAME }}/chuzone-app:1.0.0

      - name: Push stable release
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/chuzone-app:1.0.0

      - name: Create Git tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a v1.0.0 -m "Release version 1.0.0"
          git push https://${{ github.token }}@github.com/${{ github.repository }}.git v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
